// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// load_kernel_source_wrapper_cpp_export
std::string load_kernel_source_wrapper_cpp_export(const std::string& relative_path, const std::string& package);
RcppExport SEXP _opencltools_load_kernel_source_wrapper_cpp_export(SEXP relative_pathSEXP, SEXP packageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type relative_path(relative_pathSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type package(packageSEXP);
    rcpp_result_gen = Rcpp::wrap(load_kernel_source_wrapper_cpp_export(relative_path, package));
    return rcpp_result_gen;
END_RCPP
}
// load_kernel_library_wrapper_cpp_export
std::string load_kernel_library_wrapper_cpp_export(const std::string& subdir, const std::string& package, bool verbose);
RcppExport SEXP _opencltools_load_kernel_library_wrapper_cpp_export(SEXP subdirSEXP, SEXP packageSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type subdir(subdirSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type package(packageSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(load_kernel_library_wrapper_cpp_export(subdir, package, verbose));
    return rcpp_result_gen;
END_RCPP
}
// has_opencl_cpp_export
bool has_opencl_cpp_export();
RcppExport SEXP _opencltools_has_opencl_cpp_export() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(has_opencl_cpp_export());
    return rcpp_result_gen;
END_RCPP
}
// get_opencl_core_count_cpp_export
int get_opencl_core_count_cpp_export();
RcppExport SEXP _opencltools_get_opencl_core_count_cpp_export() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_opencl_core_count_cpp_export());
    return rcpp_result_gen;
END_RCPP
}
// gpu_names_cpp_export
Rcpp::CharacterVector gpu_names_cpp_export();
RcppExport SEXP _opencltools_gpu_names_cpp_export() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(gpu_names_cpp_export());
    return rcpp_result_gen;
END_RCPP
}
// opencl_device_info_cpp_export
Rcpp::List opencl_device_info_cpp_export(bool force, bool details);
RcppExport SEXP _opencltools_opencl_device_info_cpp_export(SEXP forceSEXP, SEXP detailsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type force(forceSEXP);
    Rcpp::traits::input_parameter< bool >::type details(detailsSEXP);
    rcpp_result_gen = Rcpp::wrap(opencl_device_info_cpp_export(force, details));
    return rcpp_result_gen;
END_RCPP
}
// opencl_fp64_available_cpp_export
bool opencl_fp64_available_cpp_export(bool force);
RcppExport SEXP _opencltools_opencl_fp64_available_cpp_export(SEXP forceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type force(forceSEXP);
    rcpp_result_gen = Rcpp::wrap(opencl_fp64_available_cpp_export(force));
    return rcpp_result_gen;
END_RCPP
}
// opencl_reset_device_selection_cpp_export
void opencl_reset_device_selection_cpp_export();
RcppExport SEXP _opencltools_opencl_reset_device_selection_cpp_export() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    opencl_reset_device_selection_cpp_export();
    return R_NilValue;
END_RCPP
}
// register_opencltools_ccallables_cpp_export
void register_opencltools_ccallables_cpp_export();
RcppExport SEXP _opencltools_register_opencltools_ccallables_cpp_export() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    register_opencltools_ccallables_cpp_export();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_opencltools_load_kernel_source_wrapper_cpp_export", (DL_FUNC) &_opencltools_load_kernel_source_wrapper_cpp_export, 2},
    {"_opencltools_load_kernel_library_wrapper_cpp_export", (DL_FUNC) &_opencltools_load_kernel_library_wrapper_cpp_export, 3},
    {"_opencltools_has_opencl_cpp_export", (DL_FUNC) &_opencltools_has_opencl_cpp_export, 0},
    {"_opencltools_get_opencl_core_count_cpp_export", (DL_FUNC) &_opencltools_get_opencl_core_count_cpp_export, 0},
    {"_opencltools_gpu_names_cpp_export", (DL_FUNC) &_opencltools_gpu_names_cpp_export, 0},
    {"_opencltools_opencl_device_info_cpp_export", (DL_FUNC) &_opencltools_opencl_device_info_cpp_export, 2},
    {"_opencltools_opencl_fp64_available_cpp_export", (DL_FUNC) &_opencltools_opencl_fp64_available_cpp_export, 1},
    {"_opencltools_opencl_reset_device_selection_cpp_export", (DL_FUNC) &_opencltools_opencl_reset_device_selection_cpp_export, 0},
    {"_opencltools_register_opencltools_ccallables_cpp_export", (DL_FUNC) &_opencltools_register_opencltools_ccallables_cpp_export, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_opencltools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
