# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

load_kernel_source_wrapper_cpp_export <- function(relative_path, package = "opencltools") {
    .Call(`_opencltools_load_kernel_source_wrapper_cpp_export`, relative_path, package)
}

load_kernel_library_wrapper_cpp_export <- function(subdir, package = "opencltools", verbose = FALSE) {
    .Call(`_opencltools_load_kernel_library_wrapper_cpp_export`, subdir, package, verbose)
}

has_opencl_cpp_export <- function() {
    .Call(`_opencltools_has_opencl_cpp_export`)
}

get_opencl_core_count_cpp_export <- function() {
    .Call(`_opencltools_get_opencl_core_count_cpp_export`)
}

gpu_names_cpp_export <- function() {
    .Call(`_opencltools_gpu_names_cpp_export`)
}

opencl_device_info_cpp_export <- function(force = FALSE, details = FALSE) {
    .Call(`_opencltools_opencl_device_info_cpp_export`, force, details)
}

opencl_fp64_available_cpp_export <- function(force = FALSE) {
    .Call(`_opencltools_opencl_fp64_available_cpp_export`, force)
}

opencl_reset_device_selection_cpp_export <- function() {
    invisible(.Call(`_opencltools_opencl_reset_device_selection_cpp_export`))
}

register_opencltools_ccallables_cpp_export <- function() {
    invisible(.Call(`_opencltools_register_opencltools_ccallables_cpp_export`))
}

